### ISSUE TITLE
[DEPLOYMENT] Research - jak się tworzy binarne z pythona

### ISSUE THREAD

**Issue by micmaj50** [grzjan5219/PythonGame#115]
Efektem pracy ma być skrpt *.bat który będzie generował binarkę.
Binarka ma być zawarta w jednym pliku razem ze wszystkimi bibliotekami

**Comment by Kordianzawiszewski** [comment]
Nie udało mi się stworzyć binarnej wersji gry przez błąd. Nazwa błędu: ModuleNotFoundError: No module named 'pygame.base'
