### ISSUE TITLE
Przygotowanie demo

### ISSUE THREAD

**Issue by micmaj50** [grzjan5219/PythonGame#125]

**Comment by swojtczak** [comment]
GRA:
- prezentacja gameplay
- prezentacja menu i opcji
KRÓTKA Prezentacja:
- przedstawienie zakresu wiedzy: 
  - scrum (jakie byly spotkania, kto mial jakie role, lista czlonkow zespolou i ich role
  - git (jakie operacje byly robione na gicie i ze zaczeliscie uzywac branchy)
- przedstawienie statystyk:
  - ile linii kodu pythona zostalo napisanych 
  - ile bylo commitow
  - 
-
