### ISSUE TITLE
[GAMEPLAY] Okodować system pokazujący osobisty 'highscore' gracza oraz aktualny wynik po porażce.

### ISSUE THREAD

**Issue by JarekBil** [grzjan5219/PythonGame#60]
Stworzenie samego kodu, który spowoduje, że po przegraniu lub skończeniu rozgrywki wynik gracza pojawi się w rankingu i ma się tworzyć lista wyników.

**Comment by micmaj50** [comment]
Zmiana zakresu zadania.
